### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Yung-zi** [ajsanjoaquin/mPerturb#1]
When I use 

perturb(adv, model, transforms=transforms, out_dir='/content/adv_perturb_out' ,is_numpy=True)

it occurred that 

local variable 'filename' referenced before assignment

However, when 
perturb(image_path, model, transforms=transforms, out_dir='/content/adv_perturb_out' ,is_numpy=False)

this works fine.

Why? I doubt the reason behind this is not related to filename.

**Comment by ajsanjoaquin** [comment]
The error was in the control flow. If is_numpy was true, there was no filename variable declared. 

I have removed the is_numpy altogether, so the input is strictly an image path.
